import { poppins } from "@/app/utility/fonts";
import "./globals.css";




export const metadata = {
  title: "Jiji Coco",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
      </body>
    </html>
  );
}
